services:
  localstack:
    container_name: agrosynchro-localstack
    image: localstack/localstack:latest
    restart: unless-stopped
    ports:
      - "4566:4566"                # Main LocalStack endpoint
      - "4510-4559:4510-4559"      # Additional service ports
    environment:
      - SERVICES=apigateway,sqs,s3,lambda,logs,ecs,rds,iam,sts,ec2,ecr,secretsmanager,cloudwatch
      - DEBUG=1
      - PERSISTENCE=1
      - DATA_DIR=/var/lib/localstack/data
      - HOST_TMP_FOLDER=/var/lib/localstack
      - LOCALSTACK_VOLUME_DIR=/var/lib/localstack
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - agrosynchro
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # IoT Mocks (for testing)
  mocks:
    build: ./mocks
    container_name: agrosynchro-mocks
    restart: unless-stopped
    ports:
      - "9002:9000"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
      - ENVIRONMENT=${ENVIRONMENT}
    networks:
      - agrosynchro
    depends_on:
      - localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # PostgreSQL para desarrollo local
  # En producción se usa RDS
  postgres:
    image: postgres:15
    container_name: agrosynchro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: agro
      POSTGRES_PASSWORD: agro123
      POSTGRES_DB: agrodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agrosynchro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agro"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  localstack_data:
  postgres_data:

networks:
  agrosynchro:
    driver: bridge